### PR TITLE
Ignore ultrasonic values less than 1m

### PR DESCRIPTION
**Pull request by MikeWoots**

### CODE REVIEW

**Comment by MikeWoots** [comment]
I am adding this in as a temporary fix until we develop a more robust way of handling these invalid ultrasonic readings.

**Review by arosendorff — APPROVED** [review]

**Comment by arosendorff** [comment]
> I am adding this in as a temporary fix until we develop a more robust way of handling these invalid ultrasonic readings.

Perfect, thanks Mike!

**Comment by peza8** [comment]
Is 1m safe enough? What's the highest erroneous values you've seen? 
Do the erroneous values coincide with the flag `doesUltrasonicHaveError` as `true` or not? 
That could make it safer ...

Just a bit worried about 1m being too high, because there's an edge case that can creep through this logic: 

  1. Drone starts descending. US = 0m (not correct) 
  2. Drone gets within ground range. US = distance to ground (eg 6m) 
  3. Drone starts 'seeing tree' - what I call the *SAD* distance (spontaneous appearance distance). US = 0.8m. 

With this logic, when the drone gets to step (3), it will continue into the tree. 

Thoughts @MikeWoots ? @arosendorff ?

**Comment by arosendorff** [comment]
@peza8 It's a fair point, perhaps we could ignore initial erroneous values, until we start getting valid values (e.g. > 1m), and then accept all values after that?

**Pull request closed without merging**
